### ISSUE TITLE
Prepare beepbeep repository for release

### ISSUE THREAD

**Issue by jimbeepbeep** [beepbeeptechnology/beepbeep#1]
There are a few important areas here:

1. Update the code with type hints for function inputs/outputs (i.e. `def function(input: str, input2: int=0) -> dict:`) check the latest format 
1. Add Google compliant doctrings to each function (example is in`beepbeep.bq stream_json_into_bq_with_id`)
1. Figure out how to use PyTest to test the functions
1. Write tests for functions (start with `open_json_from_local_path` in `beepbeep.utilities`)
1. Teach me how to do it

**Comment by joseignaciorm** [comment]
Task one and two: 
beepbeep/fb.py  =>
def debug_access_token(access_token: str) -> dict: Ok

def get_token_expiry_dates(debug_response: dict) -> dict: Ok

def exchange_token(api_version: str, client_id: str, client_secret: str, access_token: str) -> dict: Ok

def get_valid_insights_metrics(media_type: str) -> list: Ok

get_media_objects(api_version: str, ig_user_id: str, fields_list: list, access_token: str) -> dict: Ok

get_media_insights (api_version: str, ig_media_id: str, metrics_list: list, access_token: str) -> dict: Ok

get_user_insights (api_version: str, ig_user_id: str, metrics_list: list, period: str, since: str, until: str, access_token: str) -> dict: Ok

This is first version 0.0.1 in revision. I have created two new branches: 
1) dev branch: for developing the complete first version release like v.1.0.0
2) type-hints-docstrings branch: temporarily  branch to create type hints and docstrings

**Comment by joseignaciorm** [comment]
Done Type Hints and Docstrings in files: bq.py, fb.py, gcs.py, ps.py, sm.py, ss.py. This is the first adjustment. Pending review of them so that we can improve the implementation. Also I have changed some lines of code to improve processes...
I did a pytest for utilisties.py file but I kept on github stash in memory to continue working on it asap...

**Comment by jimbeepbeep** [comment]
All published
